// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBa9XXBZCvvm-WYMBsAARKhEvsk3p_Q7cA',
//     appId: '1:645530559881:web:a53983cec1e30345172d58',
//     messagingSenderId: '645530559881',
//     projectId: 'nej-riders',
//     authDomain: 'nej-riders.firebaseapp.com',
//     storageBucket: 'nej-riders.appspot.com',
//     measurementId: 'G-S3PWVQX1E3',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAW51L3VMjpOqNdwxF-lH-wlbgdDwM0iUk',
//     appId: '1:645530559881:android:2521026413517606172d58',
//     messagingSenderId: '645530559881',
//     projectId: 'nej-riders',
//     storageBucket: 'nej-riders.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDllmVF5a21tqkT4SPECtBFpOV4gQPCxlw',
//     appId: '1:645530559881:ios:c4d9b7d506d00669172d58',
//     messagingSenderId: '645530559881',
//     projectId: 'nej-riders',
//     storageBucket: 'nej-riders.appspot.com',
//     iosClientId: '645530559881-btau2p8p5hr0ca387phlu81qkb9a3n5s.apps.googleusercontent.com',
//     iosBundleId: 'com.nej.riders',
//   );
// }
